# Generated by Django 6.0.1 on 2026-01-26 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transmittal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=255, verbose_name='To (Recipient)')),
                ('recipient_company', models.CharField(max_length=255, verbose_name='Company')),
                ('recipient_department', models.CharField(max_length=255, verbose_name='Department')),
                ('description', models.TextField(verbose_name='Description')),
                ('remarks', models.CharField(max_length=255, verbose_name='Remarks')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('time_created', models.TimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmittals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
