# Generated by Django 6.0.1 on 2026-01-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmittals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmittal',
            name='recipient_email',
            field=models.EmailField(default='default@example.com', max_length=254, verbose_name='Recipient Email'),
            preserve_default=False,
        ),
    ]
