# Generated by Django 6.0.1 on 2026-01-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmittals', '0002_transmittal_recipient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmittal',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='transmittals/', verbose_name='Attachment'),
        ),
    ]
