# Generated by Django 6.0.1 on 2026-01-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmittals', '0003_transmittal_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transmittal',
            name='file',
        ),
        migrations.AddField(
            model_name='transmittal',
            name='is_resolved',
            field=models.BooleanField(default=False, verbose_name='Resolved'),
        ),
        migrations.AddField(
            model_name='transmittal',
            name='reference_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Reference No.'),
        ),
    ]
