# Generated by Django 6.0.1 on 2026-01-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmittals', '0004_remove_transmittal_file_transmittal_is_resolved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmittal',
            name='recipient_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted by Recipient'),
        ),
        migrations.AddField(
            model_name='transmittal',
            name='sender_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted by Sender'),
        ),
    ]
