# Generated by Django 6.0.1 on 2026-01-27 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmittals', '0005_transmittal_recipient_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmittal',
            name='recipient_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transmittal',
            name='recipient_purged',
            field=models.BooleanField(default=False, verbose_name='Purged by Recipient'),
        ),
        migrations.AddField(
            model_name='transmittal',
            name='sender_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transmittal',
            name='sender_purged',
            field=models.BooleanField(default=False, verbose_name='Purged by Sender'),
        ),
    ]
