# Generated by Django 6.0.1 on 2026-01-27 08:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmittals', '0006_transmittal_recipient_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transmittal',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Transmittal', 'verbose_name_plural': 'Transmittals'},
        ),
        migrations.RemoveField(
            model_name='transmittal',
            name='recipient_company',
        ),
        migrations.AddField(
            model_name='transmittal',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Arrived At'),
        ),
        migrations.AddField(
            model_name='transmittal',
            name='arrived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_arrived_transmittals', to=settings.AUTH_USER_MODEL, verbose_name='Marked Arrived By'),
        ),
        migrations.AddField(
            model_name='transmittal',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelled At'),
        ),
        migrations.AddField(
            model_name='transmittal',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Received At'),
        ),
        migrations.AddField(
            model_name='transmittal',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_received_transmittals', to=settings.AUTH_USER_MODEL, verbose_name='Marked Received By'),
        ),
        migrations.AddField(
            model_name='transmittal',
            name='sender_department',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sender Department'),
        ),
        migrations.AddField(
            model_name='transmittal',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Sent At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transmittal',
            name='status',
            field=models.CharField(choices=[('in_transit', 'In Transit'), ('arrived', 'Arrived'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='in_transit', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='transmittal',
            name='recipient_department',
            field=models.CharField(max_length=255, verbose_name='Recipient Department'),
        ),
        migrations.AlterField(
            model_name='transmittal',
            name='reference_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='transmittal',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='transmittal',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transmittals', to=settings.AUTH_USER_MODEL, verbose_name='From (Sender)'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Pantoc, Meycauayan, Main', max_length=100, unique=True, verbose_name='Location Name')),
                ('prefix', models.CharField(help_text='Unique prefix for reference numbers (e.g., PAN, MY, HO)', max_length=10, unique=True, verbose_name='Code/Prefix')),
                ('custodian_email', models.EmailField(blank=True, help_text='Email for notifications (uses custodian user email if blank)', max_length=254, null=True, verbose_name='Custodian Email')),
                ('address', models.TextField(blank=True, help_text='Full address of this location', null=True, verbose_name='Location Address')),
                ('is_active', models.BooleanField(default=True, help_text="Inactive locations won't appear in dropdowns", verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custodian', models.ForeignKey(blank=True, help_text='User responsible for receiving items at this location', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custodian_locations', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Custodian')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='transmittal',
            name='destination_location',
            field=models.ForeignKey(blank=True, help_text='Where the transmittal is being sent to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transmittals', to='transmittals.location', verbose_name='Destination Location'),
        ),
        migrations.AddField(
            model_name='transmittal',
            name='origin_location',
            field=models.ForeignKey(blank=True, help_text='Where the transmittal originates from', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transmittals', to='transmittals.location', verbose_name='Origin Location'),
        ),
    ]
