# Generated by Django 6.0.1 on 2026-01-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmittals', '0008_seed_default_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmittal',
            name='recipient_company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Recipient Company'),
        ),
    ]
