# Generated by Django 6.0.1 on 2026-01-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmittals', '0009_transmittal_recipient_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmittal',
            name='assigned_location_text',
            field=models.CharField(blank=True, help_text='Manually entered assigned location when not selected from dropdown', max_length=255, null=True, verbose_name='Assigned Location (Manual Entry)'),
        ),
    ]
