# Generated by Django 6.0.1 on 2026-01-29 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmittals', '0010_transmittal_assigned_location_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmittal',
            name='destination_location',
            field=models.ForeignKey(blank=True, help_text='Where the transmittal is being sent to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transmittals', to='transmittals.location', verbose_name='Destination Location'),
        ),
        migrations.AlterField(
            model_name='transmittal',
            name='origin_location',
            field=models.ForeignKey(blank=True, help_text='Where the transmittal originates from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_transmittals', to='transmittals.location', verbose_name='Origin Location'),
        ),
    ]
