# Generated by Django 6.0.1 on 2026-01-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmittals', '0012_transmittal_environment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmittal',
            name='file',
            field=models.FileField(blank=True, help_text='Optional file attachment (PDF, Image, Document, etc.)', null=True, upload_to='transmittals/', verbose_name='Attachment'),
        ),
    ]
