# Generated by Django 4.2 on 2026-02-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmittals', '0013_transmittal_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmittal',
            name='driver_remarks',
            field=models.TextField(blank=True, help_text='Driver name and vehicle plate number', null=True, verbose_name='Driver Information'),
        ),
    ]
