# Generated by Django 4.2 on 2026-02-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmittals', '0014_transmittal_driver_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmittal',
            name='receiver_signature',
            field=models.ImageField(blank=True, help_text='Digital signature of the person who received the transmittal', null=True, upload_to='transmittal_signatures/', verbose_name='Receiver Signature'),
        ),
    ]
