# Generated by Django 4.2 on 2026-02-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmittals', '0016_transmittal_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmittal',
            name='pick_remarks',
            field=models.TextField(blank=True, help_text='Optional remarks from custodian when picking the transmittal', null=True, verbose_name='Pick Remarks'),
        ),
        migrations.AddField(
            model_name='transmittal',
            name='picked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Picked At'),
        ),
        migrations.AlterField(
            model_name='transmittal',
            name='status',
            field=models.CharField(choices=[('in_transit', 'In Transit'), ('arrived', 'Arrived'), ('picked', 'Picked'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='in_transit', max_length=20, verbose_name='Status'),
        ),
    ]
