# Generated by Django 4.2 on 2026-02-20 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transmittals', '0017_transmittal_pick_remarks_transmittal_picked_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Attached image file (JPG, PNG, GIF, BMP, WebP)', upload_to='transmittals/', verbose_name='Attachment File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('transmittal', models.ForeignKey(help_text='The transmittal this attachment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='transmittals.transmittal', verbose_name='Transmittal')),
            ],
            options={
                'verbose_name': 'Transmittal Attachment',
                'verbose_name_plural': 'Transmittal Attachments',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
