# Generated by Django 4.2 on 2026-03-02 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transmittals', '0018_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of external location or recipient organization', max_length=100, verbose_name='Location/Recipient Name')),
                ('email', models.EmailField(help_text='Contact email for this external location', max_length=254, verbose_name='Email Address')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('company_address', models.TextField(verbose_name='Company Address')),
                ('contact_person', models.CharField(blank=True, help_text='Name of primary contact person at this location', max_length=255, null=True, verbose_name='Contact Person')),
                ('is_active', models.BooleanField(default=True, help_text="Inactive locations won't appear in dropdowns", verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'External Location',
                'verbose_name_plural': 'External Locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExternalTransmittal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Reference No.')),
                ('sender_email', models.EmailField(help_text='Email of the person sending the transmittal (can be external)', max_length=254, verbose_name='Sender Email')),
                ('sender_name', models.CharField(max_length=255, verbose_name='Sender Name')),
                ('sender_company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sender Company')),
                ('recipient_email', models.EmailField(help_text='Email of the person receiving the transmittal', max_length=254, verbose_name='Recipient Email')),
                ('main_type', models.CharField(choices=[('for_keep', 'For Keep'), ('for_return', 'For Return')], default='for_return', max_length=20, verbose_name='Transmittal Type')),
                ('sub_type', models.CharField(blank=True, choices=[('full', 'Full Return'), ('partial', 'Partial Return'), ('for_sample', 'Paid Sample'), ('for_keep', 'For Keep (SubType)')], help_text='For Return cases only: set when resolved', max_length=20, null=True, verbose_name='Sub Type')),
                ('description', models.TextField(help_text='Description of items being transmitted', verbose_name='Description')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('date_deadline', models.DateField(blank=True, help_text='Expected return date for For Return type', null=True, verbose_name='Return/Deadline Date')),
                ('status', models.CharField(choices=[('in_transit', 'In Transit'), ('received', 'Received'), ('open', 'Open'), ('closed', 'Closed')], default='in_transit', max_length=20, verbose_name='Status')),
                ('received_status', models.CharField(blank=True, help_text='Open/Closed for For Return transmittals', max_length=20, null=True, verbose_name='Received Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('in_transit_at', models.DateTimeField(auto_now_add=True, verbose_name='In Transit At')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Received At')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Closed At')),
                ('last_notification_date', models.DateField(blank=True, help_text='Tracks when last deadline reminder was sent (prevents duplicate emails)', null=True, verbose_name='Last Notification Date')),
                ('recipient_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_external_transmittals', to='transmittals.externallocation', verbose_name='Recipient Location')),
            ],
            options={
                'verbose_name': 'External Transmittal',
                'verbose_name_plural': 'External Transmittals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalTransmittalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Proof of delivery, RGA, or other supporting document', upload_to='external_transmittals/', verbose_name='Attachment File')),
                ('attachment_type', models.CharField(blank=True, help_text='e.g., Proof of Delivery, RGA, Signature', max_length=50, null=True, verbose_name='Attachment Type')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('uploaded_by_email', models.EmailField(blank=True, help_text='Email of person who uploaded this attachment', max_length=254, null=True, verbose_name='Uploaded By (Email)')),
                ('transmittal', models.ForeignKey(help_text='The external transmittal this attachment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='transmittals.externaltransmittal', verbose_name='External Transmittal')),
            ],
            options={
                'verbose_name': 'External Transmittal Attachment',
                'verbose_name_plural': 'External Transmittal Attachments',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalTransmittalAuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('mark_received', 'Marked Received'), ('full_return', 'Full Return Initiated'), ('partial_return', 'Partial Return Initiated'), ('paid_sample', 'Paid Sample Resolved'), ('convert_to_keep', 'Converted to For Keep'), ('closed', 'Closed'), ('admin_override', 'Admin Override')], max_length=50, verbose_name='Action')),
                ('performed_by_email', models.EmailField(blank=True, help_text='Email if performed by external sender', max_length=254, null=True, verbose_name='Performed By Email')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this action', null=True, verbose_name='Notes')),
                ('performed_by', models.ForeignKey(blank=True, help_text='User who performed this action (null if system action)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_transmittal_actions', to=settings.AUTH_USER_MODEL, verbose_name='Performed By')),
                ('required_attachment_proof', models.ForeignKey(blank=True, help_text='Attachment required for this action (RGA, signature, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_trail_entry', to='transmittals.externaltransmittalattachment', verbose_name='Proof Attachment')),
                ('transmittal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='transmittals.externaltransmittal', verbose_name='External Transmittal')),
            ],
            options={
                'verbose_name': 'External Transmittal Audit Trail',
                'verbose_name_plural': 'External Transmittal Audit Trails',
                'ordering': ['-timestamp'],
            },
        ),
    ]
