# Generated by Django 4.2 on 2026-03-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmittals', '0019_externallocation_externaltransmittal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaltransmittal',
            name='recipient_company_address',
            field=models.TextField(blank=True, help_text="Full address of the recipient's company", null=True, verbose_name='Recipient Company Address'),
        ),
        migrations.AddField(
            model_name='externaltransmittal',
            name='recipient_company_name',
            field=models.CharField(blank=True, help_text='Company or organization name', max_length=255, null=True, verbose_name='Recipient Company Name'),
        ),
        migrations.AddField(
            model_name='externaltransmittal',
            name='recipient_name',
            field=models.CharField(blank=True, help_text='Full name of the recipient', max_length=255, null=True, verbose_name='Recipient Name'),
        ),
    ]
