# Generated by Django 4.2 on 2026-03-02 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transmittals', '0020_externaltransmittal_recipient_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaltransmittal',
            name='attachments_description',
            field=models.TextField(blank=True, help_text='List or description of attachments included with this transmittal', null=True, verbose_name='Attachments Description'),
        ),
        migrations.AddField(
            model_name='externaltransmittal',
            name='external_location_text',
            field=models.CharField(blank=True, help_text='Location/address as entered by the sender', max_length=255, null=True, verbose_name='External Location'),
        ),
        migrations.AlterField(
            model_name='externaltransmittal',
            name='received_status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('close', 'Close')], help_text='Open or Close status for For Return transmittals', max_length=20, null=True, verbose_name='Received Status'),
        ),
        migrations.AlterField(
            model_name='externaltransmittal',
            name='recipient_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_external_transmittals', to='transmittals.externallocation', verbose_name='Recipient Location (Legacy)'),
        ),
    ]
