# Generated by Django 4.2 on 2026-03-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmittals', '0021_external_transmittal_text_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externaltransmittal',
            name='attachments_description',
        ),
        migrations.AddField(
            model_name='externaltransmittal',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional image or document attached by the sender', null=True, upload_to='external_transmittals/attachments/', verbose_name='Image Attachment'),
        ),
    ]
