# Generated by Django 4.2 on 2026-03-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmittals', '0022_external_transmittal_attachment_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaltransmittal',
            name='date_return',
            field=models.DateField(blank=True, help_text='The date the item is to be returned (For Return type)', null=True, verbose_name='Date of Return'),
        ),
        migrations.AlterField(
            model_name='externaltransmittal',
            name='date_deadline',
            field=models.DateField(blank=True, help_text='Hard deadline for return monitoring; reminders sent when today >= this date', null=True, verbose_name='Return Deadline Date'),
        ),
        migrations.AlterField(
            model_name='externaltransmittal',
            name='received_status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed')], help_text='Open or Closed status for For Return transmittals', max_length=20, null=True, verbose_name='Received Status'),
        ),
    ]
