# Generated by Django 4.2 on 2026-03-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmittals', '0023_externaltransmittal_date_return_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmittal',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the 5-day reminder email was sent for the current status', null=True, verbose_name='Reminder Sent At'),
        ),
        migrations.AddField(
            model_name='transmittal',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, help_text='When the status was last changed', null=True, verbose_name='Status Changed At'),
        ),
    ]
