# Generated by Django 4.2 on 2026-03-06 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transmittals', '0024_transmittal_reminder_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmittal',
            name='recipient_id',
            field=models.ForeignKey(blank=True, help_text='Internal user receiving this transmittal', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_transmittals', to=settings.AUTH_USER_MODEL, verbose_name='Recipient User'),
        ),
    ]
