# Generated by Django 4.2 on 2026-03-06 08:58

from django.db import migrations


def populate_recipient_id(apps, schema_editor):
    """
    Populate recipient_id from recipient_email by matching with User accounts.
    """
    Transmittal = apps.get_model('transmittals', 'Transmittal')
    User = apps.get_model('auth', 'User')
    
    total = 0
    matched = 0
    unmatched = []
    
    for transmittal in Transmittal.objects.filter(recipient_id__isnull=True):
        total += 1
        try:
            # Match by email (case-insensitive)
            user = User.objects.get(email__iexact=transmittal.recipient_email)
            transmittal.recipient_id = user
            transmittal.save()
            matched += 1
        except User.DoesNotExist:
            unmatched.append({
                'id': transmittal.id,
                'email': transmittal.recipient_email,
                'reference': transmittal.reference_number
            })
    
    # Print summary
    print(f"\n{'='*60}")
    print(f"RECIPIENT_ID POPULATION SUMMARY")
    print(f"{'='*60}")
    print(f"Total transmittals processed: {total}")
    print(f"Successfully matched: {matched}")
    print(f"Unmatched (no user with email): {len(unmatched)}")
    
    if unmatched:
        print(f"\nUnmatched transmittals:")
        for item in unmatched:
            print(f"  - ID: {item['id']}, Email: {item['email']}, Ref: {item['reference']}")
    
    print(f"{'='*60}\n")


def reverse_recipient_id(apps, schema_editor):
    """
    Reverse: Clear recipient_id field.
    """
    Transmittal = apps.get_model('transmittals', 'Transmittal')
    Transmittal.objects.all().update(recipient_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('transmittals', '0025_transmittal_recipient_id'),
    ]

    operations = [
        migrations.RunPython(populate_recipient_id, reverse_recipient_id),
    ]
