# Generated by Django 4.2 on 2026-03-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmittals', '0027_alter_transmittal_recipient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmittal',
            name='auto_received',
            field=models.BooleanField(default=False, help_text="Whether this transmittal was automatically received by the system after 3 days in 'picked' status", verbose_name='Auto Received'),
        ),
    ]
