# Generated by Django 5.0.14 on 2026-03-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmittals', '0030_externaltransmittal_cancellation_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaltransmittal',
            name='received_status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], help_text='Open or Closed status for For Return transmittals', max_length=20, null=True, verbose_name='Received Status'),
        ),
        migrations.AlterField(
            model_name='externaltransmittal',
            name='recipient_company_address',
            field=models.TextField(help_text="Full address of the recipient's company", verbose_name='Recipient Company Address'),
        ),
        migrations.AlterField(
            model_name='externaltransmittal',
            name='recipient_company_name',
            field=models.CharField(help_text='Company or organization name', max_length=255, verbose_name='Recipient Company Name'),
        ),
        migrations.AlterField(
            model_name='externaltransmittal',
            name='recipient_email',
            field=models.CharField(help_text='Email of the person receiving the transmittal (can be multiple separated by commas)', max_length=255, verbose_name='Recipient Email'),
        ),
        migrations.AlterField(
            model_name='externaltransmittal',
            name='recipient_name',
            field=models.CharField(help_text='Full name of the recipient', max_length=255, verbose_name='Recipient Name'),
        ),
        migrations.AlterField(
            model_name='externaltransmittal',
            name='status',
            field=models.CharField(choices=[('in_transit', 'In Transit'), ('received', 'Received'), ('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='in_transit', max_length=20, verbose_name='Status'),
        ),
    ]
