# Generated by Django 6.0.1 on 2026-01-23 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(help_text='Phone number or contact number', max_length=20)),
                ('department', models.CharField(help_text='Department name', max_length=100)),
                ('company', models.CharField(help_text='Company or organization name', max_length=100)),
                ('location', models.CharField(help_text='City or location', max_length=100)),
                ('address', models.TextField(help_text='Full address')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Registration status: pending, approved, or rejected', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='User registration date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last profile update date')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from admin', null=True)),
                ('user', models.OneToOneField(help_text='Link to Django User model', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
