# Generated by Django 6.0.1 on 2026-01-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='assigned_location',
            field=models.CharField(blank=True, help_text='Location assigned to custodian (only for custodian role)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'Regular User'), ('receiver', 'Receiver'), ('custodian', 'Custodian')], default='user', help_text='User role: user, receiver, or custodian', max_length=20),
        ),
    ]
