# Generated by Django 6.0.1 on 2026-01-28 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_assigned_location_profile_role'),
        ('transmittals', '0008_seed_default_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='assigned_location',
            field=models.ForeignKey(blank=True, help_text='Location assigned to this custodian (only for custodian role)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_staff', to='transmittals.location', verbose_name='Assigned Location'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'Regular User'), ('custodian', 'Custodian'), ('admin', 'Administrator')], default='user', help_text='User role: Regular User, Custodian, or Administrator', max_length=20, verbose_name='User Role'),
        ),
    ]
