# Generated by Django 6.0.1 on 2026-01-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_assigned_location_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='User profile image', null=True, upload_to='avatars/'),
        ),
    ]
