# Generated by Django 4.2 on 2026-02-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_useractivity_activesession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='digital_signature',
            field=models.ImageField(blank=True, help_text="User's digital signature for transmittal reports", null=True, upload_to='signatures/'),
        ),
    ]
