# Generated by Django 4.2 on 2026-02-13 08:25

from django.db import migrations, models
import django.db.models.deletion


def migrate_department_text_to_fk(apps, schema_editor):
    """
    Migrate existing text department values to Department ForeignKey.
    Creates Department objects for each unique text value found.
    """
    Profile = apps.get_model('accounts', 'Profile')
    Department = apps.get_model('accounts', 'Department')
    
    # Get all unique department text values
    unique_departments = Profile.objects.exclude(
        department__isnull=True
    ).values_list('department', flat=True).distinct()
    
    # Create Department objects for each unique text value and map profiles
    for dept_text in unique_departments:
        if dept_text:  # Skip empty strings
            # Create or get the Department object
            dept_obj, created = Department.objects.get_or_create(
                name=str(dept_text),
                defaults={'is_active': True}
            )
            # Update profiles with this text value to reference the Department object
            Profile.objects.filter(department=dept_text).update(department=dept_obj.id)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_department_alter_profile_department_and_more'),
    ]

    operations = [
        # First, migrate text data to Department FK
        migrations.RunPython(migrate_department_text_to_fk),
        
        # Finally, alter the department field to proper ForeignKey
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='accounts.department', verbose_name='Department'),
        ),
    ]
