# Generated by Django 4.2 on 2026-02-13 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_profile_department_obj_and_more'),
    ]

    operations = [
    ]