# Generated by Django 5.0.14 on 2026-03-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_profile_department_obj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='department_obj',
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, default='', help_text='Full address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.CharField(blank=True, default='', help_text='Company or organization name', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.CharField(blank=True, default='', help_text='Phone number or contact number', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='', help_text='City or location', max_length=100),
        ),
    ]
