# Generated by Django 5.0.14 on 2026-03-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_profile_department_obj_alter_profile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'Regular User'), ('custodian', 'Custodian'), ('admin', 'Administrator')], default='user', help_text='User role: Regular User, Custodian, or Administrator', max_length=20, verbose_name='User Role'),
        ),
    ]
