# Generated by Django 5.0.14 on 2026-03-30 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_profile_role'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE accounts_profile ALTER COLUMN role SET DEFAULT 'user';",
            reverse_sql="ALTER TABLE accounts_profile ALTER COLUMN role DROP DEFAULT;"
        ),
    ]
