# Generated by Django 5.0.14 on 2026-03-30 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_manual_fix_role_default'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE accounts_profile MODIFY COLUMN role varchar(20) NOT NULL DEFAULT 'user';",
            reverse_sql="ALTER TABLE accounts_profile MODIFY COLUMN role varchar(20) NOT NULL;"
        ),
    ]
