# Generated by Django 6.0.1 on 2026-01-27 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(blank=True, help_text='Auto-generated reference number', max_length=50, unique=True)),
                ('description', models.TextField(help_text='Item description')),
                ('sender_location', models.CharField(help_text='Location where item is sent from', max_length=100)),
                ('receiver_location', models.CharField(help_text='Location where item is being sent to', max_length=100)),
                ('status', models.CharField(choices=[('in_transit', 'In Transit'), ('arrived', 'Arrived'), ('received', 'Received')], default='in_transit', help_text='Current status of the item', max_length=20)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When the item was deleted', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the item was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the item was last updated')),
                ('receiver', models.ForeignKey(help_text='User who will receive the item', on_delete=django.db.models.deletion.CASCADE, related_name='received_items', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(help_text='User who sent the item', on_delete=django.db.models.deletion.CASCADE, related_name='sent_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_transit', 'In Transit'), ('arrived', 'Arrived'), ('received', 'Received')], help_text='Status that was set', max_length=20)),
                ('shipment_reference', models.CharField(blank=True, help_text='Shipment tracking number or reference', max_length=100)),
                ('delivery_proof', models.FileField(blank=True, help_text='Delivery receipt or proof document', null=True, upload_to='delivery_proofs/')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the status update')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this status update was made')),
                ('item', models.ForeignKey(help_text='Item this history belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='inventory.item')),
                ('updated_by', models.ForeignKey(help_text='Custodian who updated the status', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item Status History',
                'verbose_name_plural': 'Item Status Histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
